package zhiqiu.iztro.ui

typealias IztroLanguage = String

object ReactUiStrings {
    private val zhCN = mapOf(
        "titleBasicInfo" to "基本信息",
        "labelAlgorithm" to "安星算法",
        "algorithmDefault" to "通行版",
        "algorithmZhongzhou" to "中州派",
        "labelAstroType" to "排盘类型",
        "astroTypeHeaven" to "天盘",
        "astroTypeEarth" to "地盘",
        "astroTypeHuman" to "人盘",
        "labelElementType" to "五行局",
        "labelNominalAge" to "年龄(虚岁)",
        "labelFourPillars" to "四柱",
        "labelLunarCalendar" to "农历",
        "labelSolarCalendar" to "阳历",
        "labelChineseHour" to "时辰",
        "labelChineseZodiacSign" to "生肖",
        "labelZodiacSign" to "星座",
        "labelSoulRuler" to "命主",
        "labelBodyRuler" to "身主",
        "labelSoulPalace" to "命宫",
        "labelBodyPalace" to "身宫",
        "titleHoroscopeInfo" to "运限信息",
        "buttonNow" to "今",
        "buttonDecade" to "限",
        "buttonYear" to "年",
        "buttonMonth" to "月",
        "buttonDay" to "日",
        "buttonHour" to "时",
        "labelHoroscopeSolar" to "阳历",
        "labelHoroscopeLunar" to "农历",
        "poweredBy" to "Powered by iztro",
    )

    private val zhTW = mapOf(
        "titleBasicInfo" to "基本資訊",
        "labelAlgorithm" to "安星算法",
        "algorithmDefault" to "通行版",
        "algorithmZhongzhou" to "中州派",
        "labelAstroType" to "排盤類型",
        "astroTypeHeaven" to "天盤",
        "astroTypeEarth" to "地盤",
        "astroTypeHuman" to "人盤",
        "labelElementType" to "五行局",
        "labelNominalAge" to "年齡(虛歲)",
        "labelFourPillars" to "四柱",
        "labelLunarCalendar" to "農曆",
        "labelSolarCalendar" to "陽曆",
        "labelChineseHour" to "時辰",
        "labelChineseZodiacSign" to "生肖",
        "labelZodiacSign" to "星座",
        "labelSoulRuler" to "命主",
        "labelBodyRuler" to "身主",
        "labelSoulPalace" to "命宮",
        "labelBodyPalace" to "身宮",
        "titleHoroscopeInfo" to "運限資訊",
        "buttonNow" to "今",
        "buttonDecade" to "限",
        "buttonYear" to "年",
        "buttonMonth" to "月",
        "buttonDay" to "日",
        "buttonHour" to "时",
        "labelHoroscopeSolar" to "陽曆",
        "labelHoroscopeLunar" to "農曆",
        "poweredBy" to "Powered by iztro",
    )

    private val enUS = mapOf(
        "titleBasicInfo" to "Basic Info",
        "labelAlgorithm" to "Algorithm",
        "algorithmDefault" to "Default",
        "algorithmZhongzhou" to "Zhongzhou",
        "labelAstroType" to "Chart Type",
        "astroTypeHeaven" to "Heaven",
        "astroTypeEarth" to "Earth",
        "astroTypeHuman" to "Human",
        "labelElementType" to "Five Elements",
        "labelNominalAge" to "Nominal Age",
        "labelFourPillars" to "Four Pillars",
        "labelLunarCalendar" to "Lunar",
        "labelSolarCalendar" to "Solar",
        "labelChineseHour" to "Hour",
        "labelChineseZodiacSign" to "Chinese Zodiac",
        "labelZodiacSign" to "Zodiac Sign",
        "labelSoulRuler" to "Soul Ruler",
        "labelBodyRuler" to "Body Ruler",
        "labelSoulPalace" to "Soul Palace",
        "labelBodyPalace" to "Body Palace",
        "titleHoroscopeInfo" to "Horoscope",
        "buttonNow" to "Now",
        "buttonDecade" to "Dec",
        "buttonYear" to "Yr",
        "buttonMonth" to "Mo",
        "buttonDay" to "Day",
        "buttonHour" to "Hr",
        "labelHoroscopeSolar" to "Solar",
        "labelHoroscopeLunar" to "Lunar",
        "poweredBy" to "Powered by iztro",
    )

    private val jaJP = mapOf(
        "titleBasicInfo" to "基本情報",
        "labelAlgorithm" to "安星算法",
        "algorithmDefault" to "通行版",
        "algorithmZhongzhou" to "中州派",
        "labelAstroType" to "排盤タイプ",
        "astroTypeHeaven" to "天盤",
        "astroTypeEarth" to "地盤",
        "astroTypeHuman" to "人盤",
        "labelElementType" to "五行局",
        "labelNominalAge" to "年齢(数え年)",
        "labelFourPillars" to "四柱",
        "labelLunarCalendar" to "旧暦",
        "labelSolarCalendar" to "新暦",
        "labelChineseHour" to "時刻",
        "labelChineseZodiacSign" to "干支",
        "labelZodiacSign" to "星座",
        "labelSoulRuler" to "命主",
        "labelBodyRuler" to "身主",
        "labelSoulPalace" to "命宮",
        "labelBodyPalace" to "身宮",
        "titleHoroscopeInfo" to "運限情報",
        "buttonNow" to "今",
        "buttonDecade" to "限",
        "buttonYear" to "年",
        "buttonMonth" to "月",
        "buttonDay" to "日",
        "buttonHour" to "時",
        "labelHoroscopeSolar" to "新暦",
        "labelHoroscopeLunar" to "旧暦",
        "poweredBy" to "Powered by iztro",
    )

    private val koKR = mapOf(
        "titleBasicInfo" to "기본 정보",
        "labelAlgorithm" to "안성 알고리즘",
        "algorithmDefault" to "통행판",
        "algorithmZhongzhou" to "중주파",
        "labelAstroType" to "排盤 유형",
        "astroTypeHeaven" to "천반",
        "astroTypeEarth" to "지반",
        "astroTypeHuman" to "인반",
        "labelElementType" to "오행국",
        "labelNominalAge" to "나이(虚歲)",
        "labelFourPillars" to "사주",
        "labelLunarCalendar" to "음력",
        "labelSolarCalendar" to "양력",
        "labelChineseHour" to "시진",
        "labelChineseZodiacSign" to "띠",
        "labelZodiacSign" to "별자리",
        "labelSoulRuler" to "명주",
        "labelBodyRuler" to "신주",
        "labelSoulPalace" to "명궁",
        "labelBodyPalace" to "신궁",
        "titleHoroscopeInfo" to "運限 정보",
        "buttonNow" to "今",
        "buttonDecade" to "限",
        "buttonYear" to "年",
        "buttonMonth" to "月",
        "buttonDay" to "日",
        "buttonHour" to "時",
        "labelHoroscopeSolar" to "양력",
        "labelHoroscopeLunar" to "음력",
        "poweredBy" to "Powered by iztro",
    )

    private val viVN = mapOf(
        "titleBasicInfo" to "Thông tin cơ bản",
        "labelAlgorithm" to "Thuật toán",
        "algorithmDefault" to "Phổ thông",
        "algorithmZhongzhou" to "Trung Châu",
        "labelAstroType" to "Loại lá số",
        "astroTypeHeaven" to "Thiên bàn",
        "astroTypeEarth" to "Địa bàn",
        "astroTypeHuman" to "Nhân bàn",
        "labelElementType" to "Ngũ hành cục",
        "labelNominalAge" to "Tuổi mụ",
        "labelFourPillars" to "Tứ trụ",
        "labelLunarCalendar" to "Âm lịch",
        "labelSolarCalendar" to "Dương lịch",
        "labelChineseHour" to "Giờ",
        "labelChineseZodiacSign" to "Con giáp",
        "labelZodiacSign" to "Cung hoàng đạo",
        "labelSoulRuler" to "Mệnh chủ",
        "labelBodyRuler" to "Thân chủ",
        "labelSoulPalace" to "Mệnh cung",
        "labelBodyPalace" to "Thân cung",
        "titleHoroscopeInfo" to "Vận hạn",
        "buttonNow" to "Nay",
        "buttonDecade" to "Hạn",
        "buttonYear" to "Năm",
        "buttonMonth" to "Tháng",
        "buttonDay" to "Ngày",
        "buttonHour" to "Giờ",
        "labelHoroscopeSolar" to "Dương lịch",
        "labelHoroscopeLunar" to "Âm lịch",
        "poweredBy" to "Powered by iztro",
    )

    private val tables = mapOf(
        "zh-CN" to zhCN,
        "zh-TW" to zhTW,
        "en-US" to enUS,
        "ja-JP" to jaJP,
        "ko-KR" to koKR,
        "vi-VN" to viVN,
    )

    fun t(lang: IztroLanguage, key: String): String =
        tables[lang]?.get(key) ?: tables["zh-CN"]?.get(key) ?: key

    fun age(lang: IztroLanguage, age: Int): String = when (lang) {
        "en-US" -> "$age years old"
        "vi-VN" -> "$age tuổi"
        "ja-JP" -> "${age}歳"
        "ko-KR" -> "${age}세"
        else -> "$age 岁"
    }
}
